# Generating matrices to work with

In [2]:
import numpy as np

In [3]:
np.array([1,2,3])

array([1, 2, 3])

#### Array of all zeros

In [4]:
Z = np.zeros(10) #array of 10 zeros

In [5]:
Z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Matrix of all zeros

In [6]:
Z = np.zeros((10,10))

In [7]:
Z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### Matrix or array of ones

In [8]:
O = np.ones((10,10))
O

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [9]:
# random numbers
R = np.random.rand(3,3)

In [10]:
R

array([[0.06840704, 0.05196958, 0.55868112],
       [0.07163281, 0.68871143, 0.46676903],
       [0.10932167, 0.24249823, 0.18854197]])

In [11]:
# normal(Gaussian) distribution
G = np.random.randn()

In [12]:
G

-0.016705760405689548