# Generating matrices to work with

In [1]:
import numpy as np

In [2]:
np.array([1,2,3])

array([1, 2, 3])

#### Array of all zeros

In [3]:
Z = np.zeros(10) #array of 10 zeros

In [4]:
Z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Matrix of all zeros

In [5]:
Z = np.zeros((10,10))

In [6]:
Z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### Matrix or array of ones

In [7]:
O = np.ones((10,10))
O

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [12]:
# random numbers
R = np.random.rand(3,3)

In [13]:
R

array([[0.74653067, 0.44171868, 0.4849642 ],
       [0.34080864, 0.42354319, 0.86816845],
       [0.20222191, 0.15752042, 0.02827124]])

In [14]:
# normal(Gaussian) distribution
G = np.random.randn()