# Solving a Linear System

## Problem Ax=b
## Solution inv(A)Ax = x = inv(A)b

In [1]:
import numpy as np

In [4]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [5]:
b = np.array([1,2])
b

array([1, 2])

In [6]:
inv = np.linalg.inv(A)

In [7]:
inv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [15]:
x =  inv.dot(b.T)
x

array([0. , 0.5])

In [19]:
b

array([1, 2])

In [16]:
b.T # don't understand row and column vector both work

array([1, 2])

In [17]:
#A method solve exists to find linear solution
x = np.linalg.solve(A,b)

In [18]:
x

array([0. , 0.5])