In [2]:
import numpy as np

In [3]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(a,'\n')
print(b)

[[1 2]
 [3 4]] 

[[5 6]
 [7 8]]


#### To get a matrix multiplication use the np.dot() function.
#### Sounds odd but yes dot product for matrix multiplication

In [4]:
c = a.dot(b)
c

array([[19, 22],
       [43, 50]])

# Element wise multiplication
### use '*' to do element wise multiplication instead of '.'

In [5]:
E = a * b

In [6]:
E

array([[ 5, 12],
       [21, 32]])