In [1]:
import numpy as np

In [2]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [3]:
Ainv = np.linalg.inv(A)
Ainv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [4]:
Ainv.dot(A)

array([[1.00000000e+00, 0.00000000e+00],
       [2.22044605e-16, 1.00000000e+00]])

In [5]:
A.dot(Ainv)

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

In [6]:
det = np.linalg.det(A)

In [7]:
det

-2.0000000000000004

In [8]:
# Diagonal elements
np.diag(A)

array([1, 4])

In [9]:
np.diag([1,2]) #will return mat with 1 2 as diagonal element

array([[1, 0],
       [0, 2]])

In [10]:
np.diag([[1,2],[3,4]]) # will give the diagonal of mat passed

array([1, 4])

### inner Product(dot) and Outer product(element-wise)

In [11]:
a = np.array([1,2])
b = np.array([3,4])

In [12]:
np.inner(a,b) == a.dot(b)

True

In [13]:
np.outer(a,b)

array([[3, 4],
       [6, 8]])

In [14]:
a * b

array([3, 8])

In [21]:
### sum of diagonal
A = np.array([[1,2],[3,4,]])

In [22]:
A

array([[1, 2],
       [3, 4]])

In [23]:
np.diag(A).sum()

5

In [24]:
np.trace(A) == np.diag(A).sum()

True

# Covariance

In [26]:
x = np.random.randn(100,3)

In [27]:
cov = np.cov(x)

In [28]:
cov.shape # wrong should be a 3d matrix

(100, 100)

In [29]:
#hence always transpose the matrix for getting correct cov
cov = np.cov(x.T)

In [30]:
cov

array([[ 0.95906494, -0.05083877,  0.08184024],
       [-0.05083877,  0.87439743,  0.02786921],
       [ 0.08184024,  0.02786921,  0.96581876]])