In [1]:
import numpy as np

In [2]:
arr = np.arange(11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[4]

4

In [6]:
arr[4:8]

array([4, 5, 6, 7])

In [7]:
arr[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [8]:
 arr[0:5] = 100

In [9]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [10]:
arr = np.arange(11)

In [11]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
slice_of_arr = arr[0:6] # gets view of the original array
                        # A new copy is not created

In [13]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [15]:
slice_of_arr[:] = 100

In [16]:
slice_of_arr

array([100, 100, 100, 100, 100, 100])

In [17]:
arr

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [19]:
arr_copy = arr.copy()

In [20]:
arr_copy

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [21]:
arr_copy[:] = 99

In [22]:
arr_copy

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [23]:
arr

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [24]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [25]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [26]:
arr_2d[0][0]

5

In [28]:
arr_2d[0,0]

5

In [31]:
arr_2d[:2,1:] # row till 2 and column from 1 till end

array([[10, 15],
       [25, 30]])

In [34]:
arr_2d[1:] 

array([[20, 25, 30],
       [35, 40, 45]])

In [35]:
arr = np.arange(1,11)

In [36]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [38]:
bool_arr = arr > 5

In [39]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [41]:
arr[bool_arr] # Returns the value which are true

array([ 6,  7,  8,  9, 10])

In [43]:
# Doing in one step
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [44]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
arr[arr<3]

array([1, 2])