In [2]:
my_list = [1,2,3]

In [1]:
import numpy as np

In [7]:
arr = np.array(my_list)

In [8]:
arr

array([1, 2, 3])

In [9]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [10]:

np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(5) #range function of numpy

array([0, 1, 2, 3, 4])

In [12]:
np.zeros(3) #array of zeros

array([0., 0., 0.])

In [13]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones(4)

array([1., 1., 1., 1.])

In [15]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [2]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
np.random.rand(5) # 5 random vaules between 0 to 1

array([0.6124036 , 0.58121116, 0.03107708, 0.5749986 , 0.79778913])

In [21]:
np.random.rand(5,5)

array([[0.74085601, 0.86083128, 0.69404178, 0.04656448, 0.55797716],
       [0.53659778, 0.25429062, 0.75268567, 0.06673866, 0.46510568],
       [0.67675192, 0.11704002, 0.8492588 , 0.73241662, 0.18498424],
       [0.03025706, 0.92001647, 0.78433113, 0.20297582, 0.22497006],
       [0.41381535, 0.84567308, 0.22546737, 0.10816451, 0.18525494]])

In [23]:
np.random.randn(2) # normal distribution or gaussian distribution

array([1.25531327, 0.36485994])

In [24]:
np.random.randn(2,2)

array([[ 0.54172565, -0.76690654],
       [-1.07878668, -0.97318232]])

In [25]:
np.random.randint(1,100)

85

In [26]:
np.random.randint(1,100,10)

array([33, 41, 27, 22,  7, 68, 31, 16,  1,  3])

In [27]:
arr = np.arange(25)

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [31]:
ranarr = np.random.randint(0,50,10)

In [32]:
ranarr

array([23,  1, 15, 25, 37, 46, 26, 15, 32, 17])

In [34]:
arr.reshape(5,5) # array should have enough elements to fill the matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [39]:
ranarr

array([23,  1, 15, 25, 37, 46, 26, 15, 32, 17])

In [36]:
ranarr.max()

46

In [37]:
ranarr.min()

1

In [40]:
ranarr.argmax() # get index of max number

5

In [41]:
ranarr.argmin()

1

In [43]:
arr.shape

(25,)

In [44]:
ranarr.shape

(10,)

In [47]:
arr = arr.reshape(5,5)

In [48]:
arr.shape

(5, 5)

In [50]:
arr.dtype

dtype('int64')

In [51]:
from numpy.random import randint

In [52]:
randint(2,10)

6