# Vectors and Matrices

In [2]:
import numpy as np

In [4]:
M = np.array([[1,2],[3,4]])

In [5]:
M[0,0]

1

In [6]:
M[1,0]

3

#### a matrix function is available but use array instead

In [7]:
# matrix func
M2 = np.matrix([[1,2],[3,4]])

In [8]:
M2

matrix([[1, 2],
        [3, 4]])

In [9]:
# convert matrix to array
M2 = np.array(M2)

In [10]:
M2

array([[1, 2],
       [3, 4]])

##### Traspose

In [13]:
M2.T

array([[1, 3],
       [2, 4]])