# Example Problem

#### The admission fee at a small fair is \\$1.50 for childern and \\$4.00 for adults. On a certain day, 2200 people enter the fair and \\$5050 is collected. How many children and how many adults attended?

X1 = no. of children, X2 = no. of adult

X1 + X2 = 2200

1.5X1 + 4X2 = 5050

In [2]:
import numpy as np

In [4]:
A = np.array([[1,1],[1.5,4]])
A

array([[1. , 1. ],
       [1.5, 4. ]])

In [5]:
b = np.array([2200,5050])
b

array([2200, 5050])

In [6]:
sol = np.linalg.solve(A,b)

In [7]:
sol

array([1500.,  700.])

### childrens = 1500 and A